More work to the init template

diff --git a/templates/default/resque-init.sh.erb b/templates/default/resque-init.sh.erb
--- a/templates/default/resque-init.sh.erb
+++ b/templates/default/resque-init.sh.erb
@@ -1,4 +1,4 @@
-#!/bin/sh -e
+#!/bin/bash
 ### BEGIN INIT INFO
 # Provides:		resque
 # Required-Start:	$local_fs $remote_fs
@@ -10,10 +10,19 @@
 # Short-Description:	resque - a Redis-backed Ruby library for creating background jobs
 # Description:		resque - a Redis-backed Ruby library for creating background jobs, placing those jobs on multiple queues, and processing them later.
 ### END INIT INFO
+source /etc/init.d/functions
 
-set -e
+log_daemon_msg () {
+    # Dummy function to be replaced by LSB library.
 
-. /lib/lsb/init-functions
+    echo $@
+}
+
+log_failure_msg () {
+    # Dummy function to be replaced by LSB library.
+
+    echo $@
+}
 
 USER="<%= @user %>"
 GROUP="<%= @group %>"
@@ -24,8 +33,7 @@ RESQUE_CONF="<%= @resque_conf %>"
 BUNDLER="<%= @bundler || "/usr/local/bin/bundle" %>"
 RAKE="<%= @rake || "rake" %>"
 TASK="<%= @task || "resque:work" %>"
-PIDFILE="$ROOT/tmp/pids/resque_worker.%d.pid"
-TIMEOUT="<%= @timeout %>"
+TIMEOUT="<%= @timeout || 60 %>"
 
 # Start all the resque queues
 do_start() {
@@ -65,7 +73,7 @@ do_start_one() {
 do_start_one_do() {
   local program
   local options
-  loacl pidfile
+  local pidfile
 
   log_daemon_msg "--> Starting Resque $1-$3"
   log_daemon_msg "user $USER"
@@ -82,7 +90,7 @@ do_start_one_do() {
 
   options="$options RACK_ENV=$ENVIRONMENT QUEUES=$3"
 
-  if start-stop-daemon --start --background --quiet --pidfile $pidfile --chdir $1 --chuid $USER:$GROUP --exec /bin/bash -- -c "cd $1 && $program $options PIDFILE=$pidfile &> $1/$LOGFILE"
+  if daemon --pidfile $pidfile  --user $USER /bin/bash -- -c "cd $1 && $program $options PIDFILE=$pidfile &> $1/$LOGFILE"
   then
     log_daemon_msg "Started Resque $1-$3"
   else
@@ -120,7 +128,15 @@ do_stop_one() {
       log_daemon_msg "---> Resque $1-$2 isn't running."
     else
       log_daemon_msg "---> About to kill PID `cat $pidfile`"
-      start-stop-daemon --stop --oknodo --signal QUIT --pidfile $pidfile --retry $TIMEOUT
+      killproc --signal QUIT -p $pidfile
+      for i in `seq 1 $TIMEOUT`; do
+        checkpid $pid || break
+        sleep 1
+      done
+      if checkpid $pid ; then
+        log_failure_msg "Failed to kill Resque $1-$2 gracefully..hard shut down"
+        kill -KILL $pid >/dev/null 2>&1
+      fi
       # Many daemons don't delete their pidfiles when they exit.
       rm -f $pidfile
     fi
@@ -168,11 +184,11 @@ do_restart_one() {
 }
 
 start() {
-  do_start()
+  do_start
 }
 
 stop() {
-  do_stop()
+  do_stop
 }
 
 
